fga-eps-mds/2023-2-CAPJu-Doc

docs/projeto/eap.md

Primeira versão da Estrutura analítica do projeto CAPju
#32

Adiciona primeira versão do documento de EAP

---

docs/projeto/custos.md

Foi criado documento de gerenciamento de custos, onde os mesmos estão separados em:
closes #36 
* Custos semanais ("pagamento" dos desenvolvedores, energia, internet)
* Custos fixos (equipamentos)

Abertura do documento de custos.

---

docs/controle/cronograma_de_dojo.md

Este pull request trata da documentação do cronograma de dojo. A primeira versão foi criada em 07/10.
[#40 - [DOC] Adicionar cronograma de dojo](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/40)

#40 - Cronograma de dojo

---

docs/relatorios/semana4.md

Este pull request trata da documentação da reunião da quarta semana. Apenas uma versão contendo todas as informações da reunião realiza no dia 02/10/2023.
[#56 - [DOC] Criar Documento de Reunião com o Product Owner da 4a semana.](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/47)

#47 - Ata da semana 4

---

docs/relatorios/semana1/Kick-off.md
docs/relatorios/semana1/Primeiro_contato.md
docs/relatorios/semana2/Dojo _typescript.md
docs/relatorios/semana2/Reuniao_Lean_Inception_pt03.md
docs/relatorios/semana2/Reuniao_do_Lean_Inception_pt02.md

Este pull request trata da documentação das reuniões que aconteceram na semana 2. São 3 arquivos. O primeiro, o Dojo de TypeScript coordenado pelo EP, João Gabriel Matos, ocorrido no dia 18/09.  O segundo, a reunião sobre Lean Inception, sendo a parte 2 do desenvolvimento dessa metodologia abordado o nível de confiança para realizar cada funcionalidade. E o terceiro, a parte 03, continuação da reunião de Lean Inception, para classificação das funcionalidades em esforço, negócio e UX, além disso a definição do sequenciador e conclusão do Canvas MVP.  
[[DOC] Criar documento de relatório de eventos#47](https://app.zenhub.com/workspaces/2023-2-capju-64f9050709b930002693212a/issues/gh/fga-eps-mds/2023-2-capju-doc/47)

Eventos da semana 2

---

docs/relatorios/semana1/Kick-off.md
docs/relatorios/semana1/Primeiro_contato.md

Este pull request trata da documentação das reuniões que aconteceram na semana 1. O primeiro, a reunião de Kick-off com o cliente, com a primeira versão foi criada no dia 07/10, durante a reunião que contou com a presença do Product Owner e mútua apresentação com a equipe de desenvolvimento. O segundo, a reunião que ocorreu para o primeiro contato e conhecimento entre o time de desenvolvimento, MDS's e EPS's, onde definiram as datas das reuniões do Scrum da equipe.
[[DOC] Criar documento de relatório de eventos#47](https://app.zenhub.com/workspaces/2023-2-capju-64f9050709b930002693212a/issues/gh/fga-eps-mds/2023-2-capju-doc/47)

Eventos da semana 1

---

docs/relatorios/semana5/semana5.md

Este pull request trata da documentação da reunião da quinta semana. A primeira versão foi criada em 07/10 durante a reunião que contou com a presença do Product Owner e a ausência do professor, justificando a criação da versão inicial da documentação. A versão 2.0 corrige o valor de custo.
[#56 - [DOC] Criar Documento de Reunião com o Product Owner da 5⁰ semana.](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/59)

#59 - Ata da semana 5

---

docs/projeto/comunicacao.md

Quadro de disponibilidade da equipe adicionado na documentação do projeto
https://fga-eps-mds.github.io/2023-2-CAPJu-Doc/projeto/comunicacao/
#39

Inserção da tabela de disponibilidade dos membros

---

docs/sprints/sprint-00/sprint2-review.md

Documento da segunda ata o qual foi realizada uma Review.

Ata da segunda review

---

docs/relatorios/semana6/semana6.md

Este pull request trata da documentação da reunião da sexta semana. A primeira versão foi criada em 16/10 durante a reunião que contou com a presença do professor e a ausência do Product Owner, justificando a criação da versão inicial da documentação. A versão 2.0 incorpora as atualizações discutidas durante a reunião subsequente com a participação do P.O. Essas atualizações foram incorporadas ao mesmo arquivo da ata de reunião.
[#56 - [DOC] Criar Documento de Reunião com o Product Owner da 6⁰ semana.](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/56)

#56 - Ata da Semana 6

---

docs/controle/cronograma_de_dojo.md
docs/controle/quadro_de_conhecimento.md

Era necessário a criação de uma página na documentação do projeto com o foco de facilitar o acesso ao quadro de conhecimentos da equipe ao longo do projeto.
#38

Adicionando Quadro de conhecimentos

---

docs/relatorios/semana6/semana6.md
docs/relatorios/semana7/semana7.md
mkdocs.yml

Este pull request trata da documentação da reunião da sétima semana. Foi realizada uma correção na ata da semana 6, pois não estava presenta na documentação.
[#80 [DOC] Documentação da 7 semana de reunião](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/80)

#80 - Ata da semana 7

---

docs/projeto/riscos.md

Foram detalhados os valores dos riscos obtidos nas semanas 1 a 7 (período pré-sprints) e sprints 1 a 3 do projeto.
#82 
Para garantir a ausência de erros no markdown, como a formatação de tabelas, o procedimento envolveu a testagem usando o mkdocs local

Adicionando valores dos riscos obtidos nas semanas 1 a 7 e sprints 1 a 3

---

docs/projeto/riscos.md

Atualização do documento de riscos para a sprint 4 e sprint 5
[90](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/90)

Atualizando documento de riscos para sprint 4 e sprint 5

---

docs/relatorios/sprints/sprint03/planning.md
mkdocs.yml

Realização do documento da Planning feita no dia 04/11/2023

Realizando a Planning da Sprint 3

---

docs/relatorios/sprints/sprint06/planning.md
docs/relatorios/sprints/sprint06/review.md

Ata da reunião de review e retro da sprint 06 e a planning da sprint 07

Review, Retro e Planning da Sprint 06

---

docs/sprints/sprint04/planning.md

Esse PR inclui a Planning da sprint 04.
Inexistente.

Planning da sprint 4

---

mkdocs.yml

Adicionei no arquivo mkdics.yml, os documentos de sprint que estavam avulsos

Adicionando documentos de sprint no arquivo mkdocs.yml

---

docs/relatorios/sprints/sprint07/planning.md

Planejamento da semana com base na validação do PO realizado no dia 20/11/2023, após a reunião com o cliente.

Planning sprint 07

---

docs/relatorios/semana10/semana10.md

Ata da reunião com o PO da semana 10

Ata semana 10 PO

---

docs/projeto/EVM.md
mkdocs.yml

Adicionando EVM

---

docs/manual_de_instalacao.md
mkdocs.yml

Criando documento de manual de instalação

Criando documento de manual de instalação
